name: Test Site
permalink: pretty
plugins: _plugins
source: _themes/default
markdown: rdiscount
exclude: [config.ru, rakefile, template.haml, README.textile, Gemfile, Gemfile.lock, plugins]

#--- Misc Options ---#
google_analytics: UA-XXXXXXXX-X



